apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-backend
  namespace: student-m-puchner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-backend
  template:
    metadata:
      labels:
        app: streaming-backend
    spec:
      containers:
        - name: streaming-backend
          image: ghcr.io/manuelpuchner/streaming-htl-backend:latest
          volumeMounts:
            - mountPath: /app/persistent
              name: streaming-backend-files
          ports:
            - containerPort: 3000
      volumes:
        - name: streaming-backend-files
          persistentVolumeClaim:
              claimName: streaming-backend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-backend-svc
  namespace: student-m-puchner
spec:
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: streaming-backend
