apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-backend-pvc
  namespace: student-m-puchner
  labels:
    app: streaming-backend
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
